### ISSUE TITLE
Problems with CKAN ckanext-right_time_context

### ISSUE THREAD

**Issue by tmontanaro** [conwetlab/FIWARE-CKAN-Extensions#2]
I'm trying to install the right_time_context plugin in CKAN run within a docker container, but the plugin seems to be not recognized by CKAN.

These are the steps I'm following:

* `cd /home/tempuser/tempfolder`
* `git clone https://github.com/conwetlab/ckanext-right_time_context.git`
* `sudo su`
* `. /var/lib/docker/volumes/docker_ckan_home/_data/venv/bin/activate`
* `cd /home/tempuser/tempfolder/ckanext-right_time_context`
* `python setup.py install`
* `sudo nano /var/lib/docker/volumes/docker_ckan_config/_data/production.ini`
    * Add `right_time_context` to `ckan.plugins` and to `ckan.views.default_views`
* `cd /home/tempuser/tempfolder/ckan/contrib/docker`
* Recompile the docker container:
    * `sudo docker-compose restart ckan`

But if I see the log through `sudo docker-compose logs -f ckan` this is the error:
```
ckan          |     raise PluginNotFoundException(plugin_name)
ckan          | ckan.plugins.core.PluginNotFoundException: right_time_context
```

**Comment by fdelavega** [comment]
Can you verify whether right_time_context package has been included in the CKAN virtualenv

**Comment by fdelavega** [comment]
Can you verify that the right_time_context extension has been actually installed within the CKAN virtualenv?

**Comment by tmontanaro** [comment]
I don't know how to do it.
May I ask you to write down a few "instructions" to do it?

Thanks in advance

**Comment by agaldemas** [comment]
Hi @tmontanaro, 
you'll find installation instruction in the documentation at:
https://fiware-ckan-extensions.readthedocs.io/en/latest/installation-administration-guide.html#right-time-context
to activate environnement type:
`. /usr/lib/ckan/default/bin/activate`

**Comment by KGBis** [comment]
Hi there,
same problem here trying to add this extension into the CKAN's Dockerfile. Some help needed.

I added this line after the "setup ckan" section in its docker file:

RUN mkdir $CKAN_VENV/src/rtc && cd $CKAN_VENV/src/rtc && pip install ckanext-right_time_context

and added the extension name (as per installation instructions) in the plugins section in production.ini which I bind in the docker-compose.yml file: 3.- Add right_time_context to the ckan.plugins setting in your CKAN config file...

The problem is that after executing the docker-compose up --build command it seems the plugin is correctly installed but I get the "ckan.plugins.core.PluginNotFoundException: right_time_context" and the container dies.

I've tried several name combos, but none seems to work. In the setup.py there're a pair of lines:
 name='ckanext-right_time_context'

entry_points='''
        [ckan.plugins]
        right_time_context=ckanext.right_time_context.plugin:NgsiView
    ''',

Which name should I use?
Thanks in advance

**Comment by fdelavega** [comment]
Hi,

What CKAN docker are you using, the provided by CKAN itself?

I would recommend to use the FIWARE CKAN Docker image which came with the extension already installed.

In any case the correct name is right_time_context.

For a proper installation you should activate the virtualenv with the following command (o whatever path you have in you instance):

    . /usr/lib/ckan/default/bin/activate

Before executing the pip install command

**Comment by KGBis** [comment]
Thanks. I'm using the ckan docker distribution. After some circling around
the problem I discovered that docker was "caching" all the previous
generated images and my changes were discarded.

Anyway I'll try the fiware and see.

**Comment by KGBis** [comment]
Trying to start up the FIWARE CKAN docker distro, but it refuses to run:

ckan_1        | [prerun] Initializing or upgrading db - start
ckan_1        | Traceback (most recent call last):
ckan_1        |   File "/usr/local/bin/paster", line 11, in <module>
ckan_1        |     sys.exit(run())
ckan_1        |   File "/usr/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
ckan_1        |     invoke(command, command_name, options, args[1:])
ckan_1        |   File "/usr/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
ckan_1        |     exit_code = runner.run(args)
ckan_1        |   File "/usr/local/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
ckan_1        |     result = self.command()
ckan_1        |   File "/srv/app/src/ckan/ckan/lib/cli.py", line 217, in command
ckan_1        |     self._load_config(cmd!='upgrade')
ckan_1        |   File "/srv/app/src/ckan/ckan/lib/cli.py", line 161, in _load_config
ckan_1        |     load_environment(conf.global_conf, conf.local_conf)
ckan_1        |   File "/srv/app/src/ckan/ckan/config/environment.py", line 97, in load_environment
ckan_1        |     p.load_all()
ckan_1        |   File "/srv/app/src/ckan/ckan/plugins/core.py", line 139, in load_all
ckan_1        |     load(*plugins)
ckan_1        |   File "/srv/app/src/ckan/ckan/plugins/core.py", line 153, in load
ckan_1        |     service = _get_service(plugin)
ckan_1        |   File "/srv/app/src/ckan/ckan/plugins/core.py", line 255, in _get_service
ckan_1        |     return plugin.load()(name=plugin_name)
ckan_1        |   File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2361, in load
ckan_1        |     return self.resolve()
ckan_1        |   File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2367, in resolve
ckan_1        |     module = __import__(self.module_name, fromlist=['__name__'], level=0)
ckan_1        |   File "/srv/app/src/ckanext-privatedatasets/ckanext/privatedatasets/plugin.py", line 25, in <module>
ckan_1        |     from ckan.lib.plugins import DefaultPermissionLabels
ckan_1        | ImportError: cannot import name DefaultPermissionLabels
ckan_1        | 
ckan_1        | Traceback (most recent call last):
ckan_1        |   File "prerun.py", line 65, in <module>
ckan_1        |     init_db()
ckan_1        |   File "prerun.py", line 26, in init_db
ckan_1        |     raise e
ckan_1        | subprocess.CalledProcessError: Command '['paster', '--plugin=ckan', 'db', 'init', '-c', 'production.ini']' returned non-zero exit status 1

Any tip for it? I'm using the distro as-it. I pre-checked all configuration files, dockerfiles and the compose but I didn't see anything strange.

Thanks in advance

**Comment by fdelavega** [comment]
Is this happening with latest tag?

**Comment by KGBis** [comment]
Hi Francisco,
I tried the FIWARE/CKAN image (2.6 version iirc) but I was unable to make
the extension to work. The error was this:

ckan_1        | [prerun] Initializing or upgrading db - start
> ckan_1        | Traceback (most recent call last):
> ckan_1        |   File "/usr/local/bin/paster", line 11, in <module>
> ckan_1        |     sys.exit(run())
> ckan_1        |   File
> "/usr/local/lib/python2.7/site-packages/paste/script/command.py", line 102,
> in run
> ckan_1        |     invoke(command, command_name, options, args[1:])
> ckan_1        |   File
> "/usr/local/lib/python2.7/site-packages/paste/script/command.py", line 141,
> in invoke
> ckan_1        |     exit_code = runner.run(args)
> ckan_1        |   File
> "/usr/local/lib/python2.7/site-packages/paste/script/command.py", line 236,
> in run
> ckan_1        |     result = self.command()
> ckan_1        |   File "/srv/app/src/ckan/ckan/lib/cli.py", line 217, in
> command
> ckan_1        |     self._load_config(cmd!='upgrade')
> ckan_1        |   File "/srv/app/src/ckan/ckan/lib/cli.py", line 161, in
> _load_config
> ckan_1        |     load_environment(conf.global_conf, conf.local_conf)
> ckan_1        |   File "/srv/app/src/ckan/ckan/config/environment.py",
> line 97, in load_environment
> ckan_1        |     p.load_all()
> ckan_1        |   File "/srv/app/src/ckan/ckan/plugins/core.py", line 139,
> in load_all
> ckan_1        |     load(*plugins)
> ckan_1        |   File "/srv/app/src/ckan/ckan/plugins/core.py", line 153,
> in load
> ckan_1        |     service = _get_service(plugin)
> ckan_1        |   File "/srv/app/src/ckan/ckan/plugins/core.py", line 255,
> in _get_service
> ckan_1        |     return plugin.load()(name=plugin_name)
> ckan_1        |   File
> "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line
> 2361, in load
> ckan_1        |     return self.resolve()
> ckan_1        |   File
> "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line
> 2367, in resolve
> ckan_1        |     module = __import__(self.module_name,
> fromlist=['__name__'], level=0)
> ckan_1        |   File
> "/srv/app/src/ckanext-privatedatasets/ckanext/privatedatasets/plugin.py",
> line 25, in <module>
> ckan_1        |     from ckan.lib.plugins import DefaultPermissionLabels
> ckan_1        | ImportError: cannot import name DefaultPermissionLabels
> ckan_1        |
> ckan_1        | Traceback (most recent call last):
> ckan_1        |   File "prerun.py", line 65, in <module>
> ckan_1        |     init_db()
> ckan_1        |   File "prerun.py", line 26, in init_db
> ckan_1        |     raise e
> ckan_1        | subprocess.CalledProcessError: Command '['paster',
> '--plugin=ckan', 'db', 'init', '-c', 'production.ini']' returned non-zero
> exit status 1
>


So I came back to the ckan/ckan image (2.8.2) and added both extensions
manually into the Dockerfile before the ENTRYPOINT as follows:

RUN virtualenv $CKAN_VENV && pip -v install ckanext-right_time_context
RUN pip install --force-reinstall -v ckanext-oauth2

BTW, using the --force-reinstall flag was the only way I could get the
oauth2 extension properly installed. Otherwise, the extension was not
completely downloaded/installed.
So far, so good...

Thanks for your support!

**Comment by fdelavega** [comment]
Hi,

You are using a deprecated one I think, The one with FIWARE Extensions is:

https://hub.docker.com/r/fiware/ckan-extended

**Comment by fdelavega** [comment]
A docker-compose file can be found at:
https://github.com/conwetlab/FIWARE-CKAN-Extensions/blob/master/docker/docker-compose.yml

**Comment by KGBis** [comment]
Hi!
I've been playing around with this "CKAN-Extended" image and it boots fine.
Thanks for the tip.
As they wanted to use Gravitee for Oauth2 and this (Gravitee) requires the
callback URI to be secure (https) I've tried to follow the
https://github.com/conwetlab/ckanext-oauth2/wiki/Starting-CKAN-over-HTTPs-using-Apache
guide, but with no luck. All I managed to do is to write the token and auth
endpoints from Gravitee, do the login and that's all. No return as Gravitee
needs an HTTPS callback endpoint.

I'm not a system admin, I think this is a very important challenge to
configure this mess I have.

Could you explain me (a) how to generate the certificate and key that needs
Apache server? (b) which files may I have to modify in order to achieve a
secure server?
I ask you 'cos the file names in the guide do not match the files I've seen
inside the container. Man, there is also a big issue to do this, no vi or
vim or nano is installed in the container!!

Thanks a lot for your help.
